config/routes.rb
Rails.application.routes.draw do

  get 'connections/search'

  get 'membership_cards/exchange'
  get 'membership_cards/why'
  get 'membership_cards/generate'

  match "/404", :to => "errors#not_found", :via => :all
  match "/423", :to => "errors#permission_denied", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/503", :to => "errors#service_down", :via => :all

  get "auth/twitter/callback" => "identity#create_session"
  get "auth/facebook/callback" => "identity#create_session"

  devise_for :user

  get 'welcome/index'
  get 'maker/:id' => 'maker#show'
  get 'welcome/textoDesplegable'
  get 'welcome/wololo'

  root 'welcome#index'

  resources :categories

=begin t
  resource :request_friendships
  get 'request_friendships/send_request/:recipient', to: 'request_friendships#send_request'
  post 'request_friendships/creates', to: 'request_friendships#creates'
  get 'request_friendships/deciding_request/:rf/:choice', to: 'request_friendships#deciding_request'
  get 'request_friendships/show_pending', to: 'request_friendships#show_pending'
  get 'request_friendships/cancel_friendship', to: 'request_friendships#cancel_friendship'
=end

  get 'stories/read'
  get 'stories/read/:id' => 'stories#dbread' # read from DB
  get 'stories/example' => 'stories#example' # Caperucita Roja
  get 'stories/acquired' => 'stories#acquired'
  get 'stories/created' => 'stories#created'
  get 'stories/search', to: 'stories#search'
  resources :stories

  get 'chapters/:id' => 'chapters#show'
  post 'chapters' => 'chapters#create'
  post 'chapter_options' => 'chapters#create_options'
  put 'chapters' => 'chapters#update'
  delete 'chapters' => 'chapters#destroy'

  post 'options' => 'options#create'
  put 'options' => 'options#update'
  delete 'options' => 'options#destroy'

  get 'profiles/premium/:id', to: 'profiles#premium'
  get 'profiles/follow/:id', to: 'profiles#follow'
  get 'profiles/unfollow/:id', to: 'profiles#unfollow'
  get 'profiles/ban/:id', to: 'profiles#ban'
  resources :profiles

  get 'additions/create/:story_id' => 'additions#create'
  delete 'additions' => 'additions#delete'

  get 'comments/new/:id', to: 'comments#new'
  resources :comments

  post 'membership_cards/exchange', to: 'membership_cards#exchange'
  get 'membership_cards/exchange', to: 'membership_cards#exchange'

  get 'connections/search', to: 'connections#search'
  get 'connections/index', to: 'connections#search'

  resources :pages, :only => :show

  resources :payments, only: [:show, :destroy] do
    collection do
      get :success
      get :cancel
      post :notify
    end
  end
  get 'payment/create/:id', to: 'payments#create_story_payment'
  get 'payment/donate', to: 'payments#donation_form'
  post 'payment/donate', to: 'payments#create_donation_payment'
  get 'payment/be_premium', to: 'payments#create_mc_payment'

  get '*path' => "cuatro_cero_cuatro#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
  #validates :rating, :inclusion => 1..10
  #validates :author, presence: true

  belongs_to :profile
  belongs_to :story
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
    @idStory = params[:id_story]
  end

  def create
    if current_user.profile.present?
      @comment = Comment.new(comment_params)
      story = Story.find(@comment.story_id)
      @comment.story = story
      @comment.profile = current_user.profile
      @comment.date = Date.current
      if @comment.save
        redirect_to story
      else
        @idStory = @comment.story_id
        render :new
      end
    else
      render 'errors/permission_denied'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @idStory = params[:id_story]
  end

  def update
    @comment = Comment.find(params[:id])
    if current_user.profile.id == @comment.profile_id
      @comment.date = Date.current
      story = Story.find(@comment.story_id)
      if @comment.update(comment_params)
        redirect_to story
      else
        render :edit
      end
    else
      render 'errors/permission_denied'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if current_user.profile.id == @comment.profile_id or current_user.role_type == 'Administrator'
      story = Story.find(@comment.story_id)
      @comment.destroy
      redirect_to story
    else
      render 'errors/permission_denied'
    end
  end

  def comment_params
    params.require(:comment).permit(:title, :body, :story_id)
  end

end

app/views/comments/_form.html.erb
<%= form_for([@comment])  do |f| %>

  <div class="container">

    <% if @comment.errors.full_messages.length > 0 %>
      <div class="errors">
        <p>Se encontraron los siguientes errores al guardar el comentario:</p>
        <% @comment.errors.full_messages.each do |message| %>
          <p class="error">*<%= message  %></p>
        <% end %>
      </div>
    <% end %>

    <h3><%= name %></h3>
    <form>
      <%= f.text_field :title, placeholder: 'Título', class:'form-control' %>
      <%= f.text_area :body, placeholder: 'Comentario', class:'form-control' %>
      <%= f.hidden_field :story_id, :value => @idStory %>
      <%= f.submit 'Publicar', class: "btn btn-main" %>
      <%= link_to "Cancelar", story_path(:id => @idStory), class: "btn btn-main" %>
    </form>
  </div>

<% end %>

app/views/comments/_list.html.erb
<% name ||= "Comentarios" %>
<hr/>

<% @comments.each do |comment|%>
  <div class="container-fluid row">
    <div class="col-md-2">
      <a href="/profiles/<%= comment.profile.id %>">
      <%= image_tag(comment.profile.avatar, class: "img-circle img-responsive") %>
      <p class="text-center"><%= comment.profile.user.name %></p>
      </a>
    </div>
    <div class="col-md-8">
      <h4><%= comment.title %></h4>
      <p><%= comment.body %><p>
      <small><%= comment.date.strftime("%A, %dth %B %Y") %></small>
    </div>
    <div class="col-md-2 text-right">
      <% if current_user.profile == comment.profile %>
      <%= link_to "", edit_comment_path(comment, :id_story => id), class: "glyphicon glyphicon-pencil" %>
      &nbsp;
      <% end %>
      <% if current_user.profile == comment.profile or current_user.role_type == 'Administrator' %>
      <%= link_to "", comment, method: :delete, :id_story => id, class: "glyphicon glyphicon-remove" %>
      <% end %>
    </div>
  </div>
  <hr/>
<% end %>

<% if current_user.present? %>
  <%= link_to "Nuevo comentario", new_comment_path(:id_story => id), class: "btn btn-main", :method => :get %>
<% end %>

app/views/comments/edit.html.erb
<%= render "comments/form", name: "Editar comentario" %>

app/views/comments/new.html.erb
<%= render "comments/form", name: "Nuevo comentario" %>