config/routes.rb
Rails.application.routes.draw do

  get 'connections/search'

  get 'membership_cards/exchange'
  get 'membership_cards/why'
  get 'membership_cards/generate'

  match "/404", :to => "errors#not_found", :via => :all
  match "/423", :to => "errors#permission_denied", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/503", :to => "errors#service_down", :via => :all

  get "auth/twitter/callback" => "identity#create_session"
  get "auth/facebook/callback" => "identity#create_session"

  devise_for :user

  get 'welcome/index'
  get 'maker/:id' => 'maker#show'
  get 'welcome/textoDesplegable'
  get 'welcome/wololo'

  root 'welcome#index'

  resources :categories

=begin t
  resource :request_friendships
  get 'request_friendships/send_request/:recipient', to: 'request_friendships#send_request'
  post 'request_friendships/creates', to: 'request_friendships#creates'
  get 'request_friendships/deciding_request/:rf/:choice', to: 'request_friendships#deciding_request'
  get 'request_friendships/show_pending', to: 'request_friendships#show_pending'
  get 'request_friendships/cancel_friendship', to: 'request_friendships#cancel_friendship'
=end

  get 'stories/read'
  get 'stories/read/:id' => 'stories#dbread' # read from DB
  get 'stories/example' => 'stories#example' # Caperucita Roja
  get 'stories/acquired' => 'stories#acquired'
  get 'stories/created' => 'stories#created'
  get 'stories/search', to: 'stories#search'
  resources :stories

  get 'chapters/:id' => 'chapters#show'
  post 'chapters' => 'chapters#create'
  post 'chapter_options' => 'chapters#create_options'
  put 'chapters' => 'chapters#update'
  delete 'chapters' => 'chapters#destroy'

  post 'options' => 'options#create'
  put 'options' => 'options#update'
  delete 'options' => 'options#destroy'

  get 'profiles/premium/:id', to: 'profiles#premium'
  get 'profiles/follow/:id', to: 'profiles#follow'
  get 'profiles/unfollow/:id', to: 'profiles#unfollow'
  get 'profiles/ban/:id', to: 'profiles#ban'
  resources :profiles

  get 'additions/create/:story_id' => 'additions#create'
  delete 'additions' => 'additions#delete'

  get 'comments/new/:id', to: 'comments#new'
  resources :comments

  post 'membership_cards/exchange', to: 'membership_cards#exchange'
  get 'membership_cards/exchange', to: 'membership_cards#exchange'

  get 'connections/search', to: 'connections#search'
  get 'connections/index', to: 'connections#search'

  resources :pages, :only => :show

  resources :payments, only: [:show, :destroy] do
    collection do
      get :success
      get :cancel
      post :notify
    end
  end
  get 'payment/create/:id', to: 'payments#create_story_payment'
  get 'payment/donate', to: 'payments#donation_form'
  post 'payment/donate', to: 'payments#create_donation_payment'
  get 'payment/be_premium', to: 'payments#create_mc_payment'

  get '*path' => "cuatro_cero_cuatro#index"

end

app/models/story.rb
class Story < ActiveRecord::Base
  #validates :frontpage, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :language, presence: true
  #Precio debe ser minimo 0
  #validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than => 0}
  # :release_date debe estar en pasado
  validates_associated :chapters
  #validate :check_date

  after_create :save_categories

  has_many :chapters
  has_many :comments
  has_many :payments, as: :good
  has_many :has_categories
  has_many :categories, through: :has_categories

  # TODO Validar en after_create?
  # validates :categories, presence: true

  #TODO
  #Hasta que no se solucione el problema con la gema de imagenes
  #debe poder no ponerse portada (para poder hacer pruebas)
  #validates :cover, presence: true

  #Creador perfil
  #TODO Ahora el foreign key es "id" porque si no peta, hay que arreglarlo
  belongs_to :creatorProfile, class_name: "Profile", foreign_key: "profile_id"

  #Setter de la relación
  def categories=(value)
    @categories=value
  end
=begin
  def check_date
    date1 = release_date - 1
    date2 = Time.now()

    date2 > date1
  end
=end
  # Devuelve TRUE si la historia ha sido adquirida por el usuario 'user'.
  def has_been_acquired_by_user?(user)
    current_user_profile = Profile.find_by(user_id: user.id)
    addition = Addition.find_by(profile_id: current_user_profile, story_id: self.id)
    addition != nil
  end

  private

  def save_categories
    @categories.each do |category_id|
      HasCategory.create(category_id: category_id, story_id: self.id)
    end
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
before_action :authenticate_user!, except: [:example ]
  #GET /stories
  def index
    @stories = Story.all
  end

  # Devuelve una lista con las historias adquiridas por
  # el usuario logueado o un aviso si no tiene
  def acquired
    profile  = Profile.find_by(user: current_user)
    additions = Addition.where(profile_id: profile)
    @stories = []
    additions.each do |addition|
      @stories << addition.story
    end
    if @stories.blank?
      flash.now.alert = 'No se han encontrado resultados'
    end
  end

  # Devuelve una lista con las historias creadas por
  # el usuario logueado o un aviso si no tiene
  def created
    #profile  = Profile.find_by(user: current_user)
    @stories = current_user.profile.stories
    if @stories.blank?
      flash.now.alert = 'No se han encontrado resultados'
    end
  end

  #GET /stories/read/:id
  def read
    # @story = Story.find(params[:id])
  end

  def example
    @story = Story.find_by_title('Caperucita Roja')
    render 'stories/dbread'
  end

  def dbread
    @story = Story.find(params[:id]);
  end

  #GET /stories/:id
  def show
    begin
    @story = Story.find(params[:id])
    @comments = @story.comments
    rescue ActiveRecord::RecordNotFound => e
      render 'errors/not_found'
    end
  end

  #GET /stories/new
  def new
    @story = Story.new
    @categories = Category.all
  end

  def edit
    begin
      @story = set_story
    end
  end

  #POST /stories
  def create
    @story = Story.new(story_params)
    @story.num_purchased = 0
    @story.published = false
    @story.creatorProfile = current_user.profile
    @story.categories = params[:categories]
    @categories = Category.all

    # No se muestra en esta versión
    @story.language = "SPANISH"
    @story.price = 0.0

    if @story.save
      redirect_to @story
    else
      @categories = Category.all
      flash[:alert] = 'Error almacenando historia'
      render :new
    end
  end

  def update
    @story = set_story
    @story.categories = params[:categories]
    @categories = Category.all
    #if is_current_profile? @profile # No permitas que un usuario edite un perfil que no es suyo

    #puts(story_params)
    @newCategories = params[:categories]
    logger.debug "--------------- new categories #{@newCategories}"

    if (!@newCategories.nil?)
      @localCategories = Category.find(@newCategories)
      logger.debug "---------------- localCategories #{@localCategories.to_ary}"
    end

    if @localCategories == nil
      flash.now.alert = 'Es obligatorio añadir una categoría al menos'
      render :edit
      logger.debug "------------- ENTRA!!!"

    else
      @other = @story.categories.to_ary
      logger.debug "------------- my categories #{@other}"
      @story.categories.delete_all
      logger.debug "------------- my categoriesVacía #{@other}"
      @story.categories.push(@localCategories.to_ary)
      logger.debug "------------- my categories #{@story.categories.to_ary}"
      #@story.assign_attributes(:categories => @newCategories)
      #@originalCaterogiesStory = @story.categories
      #logger.debug "----------- my categories #{@originalCaterogiesStory}"

      if @story.update(story_params_update)

        #if @story.update_attributes(params[:category])
        redirect_to @story
      else
        render :edit
      end

    end


    #else
     # render 'errors/permission_denied'
    #end
  end

  def story_params


    # Con frontpage -> params.require(:story).permit(:title,:description,:cover,:frontpage,:language,:price,:release_date,:published,:num_purchased)
    params.require(:story).permit(:title,:description,:cover,:frontpage,:language,:price,:release_date,:published,:num_purchased,:category_id)
  end

  def story_params_update
    params.require(:story).permit(:title,:description,:cover,:frontpage,:language,:price,:release_date,:published,:num_purchased,:category_id)
  end


  def search

    @categories = Category.all
    @stories = Array.new()

    if params[:q]
      @q = params[:q].downcase #Obtiene el texto de búsqueda
      @selectedCategories = params[:checkboxform] #Obtiene las categorías seleccionadas
      query = 'lower(title) like :q OR lower(description) like :q OR lower(language) like :q and published = true'
      #logger.debug "-------------------------------- q tiene el valor #{@q}"
      #logger.debug "-------------------------------- selectedCategories tiene el valor #{@selectedCategories}"

      @localCategories = Array.new()
      if @selectedCategories == nil #Comprueba si nos llega el array de categorías vacío, en cuyo caso usaremos todas las categorías
        @localCategories = Category.all
      else #En caso contrario, buscamos las categorías seleccionadas
        @localCategories = Category.find(@selectedCategories)
      end

      #Descomentar para comprobar el contenido de localCategories
      #for aux in @localCategories
        #logger.debug "------------------------------ localCategory #{aux.name}"
      #end

      if @q
        @localStories = Story.where(query,{q: "%#{@q}%"}) #Realizamos la query que busca por el título indicado
        @firstStepStories = Array.new()
        for aux in @localStories #Para cada historia de @localStories
          #Descomentar para comprobar el título de cada hsitoria encontrada
          #logger.debug"__________________________ localStory #{aux.title}"
          @auxCategrs = aux.categories
          for aux2 in @auxCategrs #De cada historia, recorremos sus categorías
            #Descomentar para comprobar el listado de categorías la historia
            #logger.debug"__________________________ localStoryGenre #{aux2.name}"
            for aux3 in @localCategories #Ahora, comprobamos que comprenda las categorías que estamos buscando
              #Descomentar para comprobar las categorías deseadas
              #logger.debug"__________________________ estamos buscando con la categoría #{aux3.name}"
              if aux2 == aux3 #Vamos comparando categorías propias y las deseadas
                #Descomentat para comprobar si hay coincidencias
                #logger.debug"__________________________ coincidencia #{aux2.name} - #{aux3.name}"
                @firstStepStories.push(aux) #Vamos añadiendo las historias cada vez que coincidan
              end
            end
          end
        end
        @stories = @firstStepStories.uniq #Finalmente, devolvemos la lista, sin repetir elementos
      end
    end


    #A partir de aquí, territorio Apache, desconocido... O.o

    if params[:category_id]
      category_id = params[:category_id].to_i
      if category_id > 0
        @category = Category.find(category_id)
        stories_by_category = @category.stories
      end
      if @stories and category_id > 0
        @stories = @stories & stories_by_category # Intersección de conjunto en Ruby2
      else
        @stories = stories_by_category
      end
    end

    if params[:q] == nil and params[:category_id] == nil
      @stories = Story.all
    end
  end

  def set_story
    @story=Story.find(params[:id])
  end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<script>
  document.onload=function() {
    previewFile();  //calls the function named previewFile()
  }

  function previewFile() {
    var preview = document.querySelector('img'); //selects the query named img
    var file    = document.querySelector('input[type=file]').files[0]; //sames as here
    var reader  = new FileReader();
    reader.onloadend = function () {
      preview.src = reader.result;
      document.getElementById("story_cover").setAttribute("value",reader.result);
    }
    if (file) {
      reader.readAsDataURL(file); //reads the data as a URL
    } else {
      preview.src = "";
    }
  }
</script>

<% name ||= "Crear" %>

<h1>Crear historia</h1>

<%= form_for(@story) do |f|%>
  <% if @story.errors.full_messages.length > 0 %>
    <div class="errors">
      <p>Se encontraron los siguientes errores al guardar la historia:</p>
      <% @story.errors.full_messages.each do |message| %>
        <p class="error">*<%= message  %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <label for="title">Portada</label><br>
    <%= f.text_field :cover, placeholder: "URL de la portada", class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="title">Título</label><br>
    <%= f.text_field :title, placeholder: "Título", class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="description">Sinopsis</label><br>
    <%= f.text_area :description, placeholder: "Sinopsis", class: "form-control" %>
  </div>
  <!-- No se muestra en esta versión -->
  <!--<div class="form-group">
    <label for="language">Idioma</label><br>
    <%= f.text_field :language, placeholder: "Idioma", class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="price">Precio</label><br>
    <%= f.number_field :price, placeholder: "Precio", class: "form-control"  %>
  </div>-->
  <div class="form-group">
    <label for="categorias">Elija los géneros (al menos uno)</label>
    <% @categories.each do |category| %>
      <br/><%= check_box_tag "categories[]", category.id %>&nbsp;<%= category.name %>
    <% end %>
  </div>

  <div class="field" style="margin-top: 20px;">
    <%= f.submit "Guardar", class: "btn btn-main" %>
  </div>

<%end%>

app/views/stories/_header.html.erb
<div class="row">
  <div class="col-md-9">
    <h1>Historias</h1>
  </div>
  <div class="col-md-3">
    <form action="/stories/search" method="get" role="form">
      <div class="form-group has-feedback index-searchbox">
        <input class="form-control" type="text" name="q" placeholder="Buscar..." value="<%= @q %>" />
        <i class="glyphicon glyphicon-search form-control-feedback"></i>
      </div>
    </form>
  </div>
</div>

<!-- Tabs para cada listado -->
<ul class="nav nav-tabs nav-justified">
  
  <!-- Todas las historias (todos los usuarios) -->
  <li <% if option == "all" %>class="active"<% end %> role="presentation">
    <%= link_to "Todas", stories_path, class:"btn btn-default" %>
  </li>

  <!-- Historias adquiridas (sólo usuarios logueados) -->
  <% if user_signed_in? %>

    <li <% if option == "acquired" %>class="active"<% end %> role="presentation">
      <%= link_to "Adquiridas", stories_acquired_path, class:"btn btn-default" %>
    </li>

    <!-- Historias creadas (sólo usuarios premium y admins) -->
    <% unless current_user.role_type == "FreeUser" %>
      
      <li <% if option == "created" %>class="active"<% end %> role="presentation">
        <%= link_to "Creadas", stories_created_path, class:"btn btn-default" %>
      </li>

    <% end %>

  <% end %>

</ul>
<br/>

app/views/stories/_list.html.erb
<% unless @stories.blank? %>
	<% @stories.each_slice(4) do |stories| %>
  	<div class="row">
    	<% stories.each do |story| %>
      	<div class="col-md-3">
        	<%= render 'stories/story_slot', story: story %>
      	</div>
    	<% end %>
  	</div>
	<% end %>
<% else %>
	<p class="alert-alert">No se han encontrado resultados</p>
<% end %>

app/views/stories/_story.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="story-block story-metadata">
      <div class="text-center">
        <div class="story">
          <!-- TODO: Hacer que la imagen se posicione igual que como en las imágenes del diseñador -->
          <%= render 'stories/story_cover', story: story %>
        </div>
      </div>
      <h3 class="text-center"><a href="/profiles/<%= story.creatorProfile.id %>"><%= story.creatorProfile.name %></a></h3>
      <hr/>
      <p><b>Géneros:</b></p>
      <!-- Solución prvisional -->
      <% story.categories.each do |category| %>
      <p>&#9679; <%= category.name %></p>
      <% end %>
      <!-- No se muestra en esta versión -->
      <!--<p>Idioma: <%= story.language %></p>-->
      <!-- TODO: Mejorar la forma en la que se muestra el idioma -->
      <p><b>Fecha de publicación:</b> <%= story.release_date ? story.release_date.strftime('%d/%m/%Y') : 'Sin fecha' %></p>
      <% if current_user.present? %> <!-- Evitar "NilException" -->
        <% if story.creatorProfile.id == current_user.profile.id %>
          <hr/>
          <div class="text-center" style="margin-bottom: 10px;">
            <%= link_to "Editar información", edit_story_path(@story), class:"btn btn-main" %>
          </div>
          <div class="text-center" style="margin-bottom: 10px;">
            <%= button_to 'Ir al editor de historias', "/maker/#{story.id}",  class: 'btn btn-main', method: :get %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-8">
    <div class="story-block story-data">
      <h2 class="text-center"><%= story.title %></h2>
      <hr/>
      <h4><strong>Resumen</strong></h4>
      <p><%= story.description %></p>
      <div class="text-center">
        <% unless current_user.nil? %>
          <% unless story.has_been_acquired_by_user?(current_user) or
              story.creatorProfile.id == current_user.profile.id %>
            <form action='/additions/create/<%=story.id%>' method="get">
            <!-- No hay pagos en esta versión -->
            <!--<form action='/payment/create/<%=story.id%>' method="get">-->
              <button type="submit" class="btn btn-adquirir">
                <p class="btn-label">Adquirir historia</p>
                <!-- No se muestra en esta versión -->
                <!--<p><b>Precio:</b><span> <%= story.price %> €</span></p>-->
              </button>
            </form>
          <% else %>
            <% if story.chapters.any? %>
              <form action="/stories/read/<%= story.id %>" method="get">
                <button type="submit" class="btn btn-leer">
                  <p class="btn-label">Leer</p>
                </button>
              </form>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- Comentarios -->
    <div class="story-block story-comments">
      <h3>Comentarios</h3>
      <%= render 'comments/list', id: @story.id %>
    </div>
    
  </div>
</div>

app/views/stories/_story_slot.html.erb
<div class="text-center">
  <a href="/stories/<%= story.id %>">
  <div class="story">
    <p class="title"><%= story.title %></p>
      <%= render 'stories/story_cover', story: story %>
    <div class="story-info">
      <p class="author"><%= story.creatorProfile.name %></p>
    </div>
  </div>
  </a>
</div>

app/views/stories/_valoration.html.erb
<div class="valoration">
  <!-- TODO: Lógica de la valoración aún por terminar -->
  <% (1..valoration/2).each do |i| %>
    <img class="valoration-star" src="/assets/star_3.png" />
  <% end %>
  <img class="valoration-star" src="/assets/star_1.png" />
</div>

app/views/stories/acquired.html.erb
<%= render 'stories/header', option: "acquired" %>
<%= render 'stories/list' %>

app/views/stories/created.html.erb
<%= render 'stories/header', option: "created" %>
<%= render 'stories/list' %>

app/views/stories/dbread.html.erb
<div class="container">

  <!-- Título y autor -->
  <div class="text-center book-title">
    <h1><%= @story.title %></h1>
    <h3><%= @story.creatorProfile.name %></h3>
  </div>

  <!-- Libro -->
  <div ng-app="reader" ng-controller="ReaderController" class="row row-eq-height book">
    
    <!-- Página izquierda -->
    <div class="col-md-3 col-md-offset-1 page-left">
    </div>

    <!-- Página derecha -->
    <div class="col-md-5 page-right">
        
      <!--Animación de loading-->
      <h2 class="text-center" ng-show="loading">
        <img src="/ripple.svg" alt="Loading...">
      </h2>

      <!-- Contenido de la página -->
      <article ng-hide="loading">

        <!-- Capítulo anterior -->
        <a ng-show="parent_id" ng-click="setChapter(parent_id)" class="book-back">
          <p><span class="glyphicon glyphicon-chevron-left"></span>&nbsp;Atrás</p>
        </a>

        <!-- Cuerpo del capítulo -->
        <p ng-bind-html="current_chapter? current_chapter.body : 'No hay cuerpo del capitulo/nodo'"></p>
        <p ng-hide="options.length > 0" class="text-center"><b>FIN</b></p>

        <!-- Lista de opciones -->
        <ul id="options-list" class="list-unstyled">
          <li ng-repeat="option in options">
            <a ng-click="setChapter(option.child_id)" class="book-option">
              <p><span class="glyphicon glyphicon-chevron-right"></span>&nbsp;{{option.option}}</p>
            </a>
          </li>
        </ul>

      </article>

    </div>

  </div>

</div>

<script type="text/javascript" charset="utf-8">
  
  (function(){
    angular.module("reader", ["ngSanitize"]).controller("ReaderController", function($scope, $sanitize){
      $scope.loading = true;
      $scope.parent_id = null;
      $scope.options = [];
      $scope.current_chapter = null;
      $scope.setChapter = function setChapter(id){
        $scope.loading = true;
        $.get("/chapters/"+id+".json", function(chapter){
          var first_parent = chapter.parent_options[0];
          chapter.body = $sanitize(chapter.body);
          console.log((chapter.body));
          $scope.options = chapter.child_options;
          $scope.parent_id = first_parent? first_parent.parent_id: null;
          $scope.current_chapter = chapter;
          $scope.loading = false;
          $scope.$digest();
        })
      };
      $scope.setChapter(<%= @story.chapters.first.id %>);
    });
  })();

</script>

app/views/stories/edit.html.erb
<%#= render "stories/form", name: "Edit story" %>
<h1>Editar información de la historia</h1>

<%= form_for(@story) do |f|%>
    <% if @story.errors.full_messages.length > 0 %>
        <div class="errors">
          <p>Se encontraron los siguientes errores al guardar la historia:</p>
          <% @story.errors.full_messages.each do |message| %>
              <p class="error">*<%= message  %></p>
          <% end %>
        </div>
    <% end %>

    <div class="form-group">
      <label for="title">Portada</label><br>
      <% unless @story.cover.present? %>
          <!-- Solución provisional -->
          <% cat = I18n.transliterate(@story.categories.first.name).downcase %>
          <img class="cover-image" title="<%= @story.title %>" src="/assets/categories_covers/<%= cat %>.jpg" />
      <% else %>
          <img class="cover-image" title="<%= @story.title %>" src="<%= @story.cover %>" />
      <% end %>
      <br/>
      <br/>
      <%= f.text_field :cover, placeholder: "URL de la portada", class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="title">Título</label><br>
      <%= f.text_field :title, placeholder: "Título", class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="description">Sinopsis</label><br>
      <%= f.text_area :description, placeholder: "Sinopsis", class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="categorias">Elija los géneros (al menos uno)</label>
      <% @categories=Category.all%><br>

      <% @categories.each do |category|%>
          <%#= hidden_field_tag "story[category_ids][]", nil%>
          <%#= check_box_tag "story[category_ids][]", category.id, @story.category_ids.include?(category.id), id:dom_id(category)%>
          <%#= label_tag dom_id(category), category.name%>
          <%= check_box_tag "categories[]", category.id,  @story.categories.ids.include?(category.id)%>
          <%= category.name%><br>
      <%end%>



      <%# @categories.each do |category| %>
          <%# @story.categories.each do |categoryStory| %>
              <%# if (category.id) == (categoryStory.id)%>
                  <!--<br/><%#= check_box_tag "categories[]", category.id , true%>&nbsp;<%#= category.name %>
              <%#else%>
                  <br/><%#= check_box_tag "categories[]", category.id %>&nbsp;<%#= category.name %>
              <%#end%>
          <%#end%>
      <%# end %>-->

      <%#= submit_tag "Guardar"%>
      <div class="field" style="margin-top: 20px;">
        <%= f.submit "Guardar", class: "btn btn-main" %>
      </div>
    </div>

    <!--<div class="field">
      <%#= f.submit "Guardar", class: "btn btn-primary" %>
    </div>-->



<%end%>

app/views/stories/index.html.erb
<%= render 'stories/header', option: "all" %>
<%= render 'stories/list' %>

app/views/stories/read.html.erb
<style>
  .glyphicon{
    font-size: 1em !important;
  }
</style>
<div data-ng-app="app">
    <header class="page-header">
        <h1 class="text-primary"><em>Rapsoda</em>: Lector</h1>
    </header>
    <div data-ng-controller="ReaderController as reader">
        <span class="btn btn-success btn-file">
            <span class="glyphicon glyphicon-cloud-upload"></span>
            Examinar&hellip;
            <input  type="file" id="textfile"
                    accept="application/json"
                    onchange="angular.element(this).scope().reader.fileChange()">
        </span>
        <span id="filename"></span>
        <span class="help-block">Sube un archivo JSON</span>
        <hr
        data-ng-show="reader.history.chunk">
        <%= render 'angular_story' %>
    </div>
    <hr />
</div>
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js"></script>
<script type="text/javascript" charset="utf-8">
  var app = angular.module('app', []);

  app.controller('ReaderController', function($scope){
    var file_input = document.getElementById('textfile');
    var container  = document.getElementById('show-text');
    var filename   = document.getElementById('filename');
    var self = this;
    self.story = {};
    self.selectedOption = "aaaa";
    self.readtext = function(file){
      var reader  = new FileReader();
      reader.onload = function(event){
        var result = event.target.result;
        try{
          self.story = JSON.parse(result);
          parseHistory(self.story);
          angular.element(filename).text(file.name);
        }
        catch(err){
          self.story.error = true;
          throw new SyntaxError('Error parsing input file');
        }
        $scope.$apply();
      };
      reader.readAsText(file);
    };
    self.fileChange = function(){
      self.readtext(file_input.files[0]);
    };

    function setChunk(id){
      self.story.chunk = self.story.chunks.filter(function(chunk){
        return chunk.id === id;
      })[0];
      console.log("current chunk: ");
      console.log(self.story.chunk);
    }
    function parseHistory(file){
      self.story = file;
      setChunk('c1');
    }
    self.al = function(o){window.alert(o);};
    self.setChunk = setChunk;
  });
</script>

app/views/stories/search.html.erb
<div class="row">
  <div class="col-md-9">
      <%= render 'stories/list' %>
  </div>
  <div class="col-md-3">
    <div class="story-search-params">
      <form action="/stories/search" method="get" role="form">
        <div class="form-group has-feedback">
          <input class="form-control" type="text" name="q" placeholder="Buscar..." value="<%= @q %>" />
          <i class="glyphicon glyphicon-search form-control-feedback"></i>
        </div>
        <h3 class="text-center">Géneros</h3>
        <hr/>
        <% @categories.each do |category| %>
          <!-- Con esto, se crea un array llamado checkboxform al que iremos añadiendo cada categoría -->
          <div class="category-params">
            <%=check_box_tag "checkboxform[]",category.id%>&nbsp;<%=category.name%><br/>
          </div>
        <% end %>
      </form>
    </div>
  </div>
</div>

app/views/stories/show.html.erb
<%= render @story %>