config/routes.rb
Rails.application.routes.draw do

  get 'connections/search'

  get 'membership_cards/exchange'
  get 'membership_cards/why'
  get 'membership_cards/generate'

  match "/404", :to => "errors#not_found", :via => :all
  match "/423", :to => "errors#permission_denied", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/503", :to => "errors#service_down", :via => :all

  get "auth/twitter/callback" => "identity#create_session"
  get "auth/facebook/callback" => "identity#create_session"

  devise_for :user

  get 'welcome/index'
  get 'maker/:id' => 'maker#show'
  get 'welcome/textoDesplegable'
  get 'welcome/wololo'

  root 'welcome#index'

  resources :categories

=begin t
  resource :request_friendships
  get 'request_friendships/send_request/:recipient', to: 'request_friendships#send_request'
  post 'request_friendships/creates', to: 'request_friendships#creates'
  get 'request_friendships/deciding_request/:rf/:choice', to: 'request_friendships#deciding_request'
  get 'request_friendships/show_pending', to: 'request_friendships#show_pending'
  get 'request_friendships/cancel_friendship', to: 'request_friendships#cancel_friendship'
=end

  get 'stories/read'
  get 'stories/read/:id' => 'stories#dbread' # read from DB
  get 'stories/example' => 'stories#example' # Caperucita Roja
  get 'stories/acquired' => 'stories#acquired'
  get 'stories/created' => 'stories#created'
  get 'stories/search', to: 'stories#search'
  resources :stories

  get 'chapters/:id' => 'chapters#show'
  post 'chapters' => 'chapters#create'
  post 'chapter_options' => 'chapters#create_options'
  put 'chapters' => 'chapters#update'
  delete 'chapters' => 'chapters#destroy'

  post 'options' => 'options#create'
  put 'options' => 'options#update'
  delete 'options' => 'options#destroy'

  get 'profiles/premium/:id', to: 'profiles#premium'
  get 'profiles/follow/:id', to: 'profiles#follow'
  get 'profiles/unfollow/:id', to: 'profiles#unfollow'
  get 'profiles/ban/:id', to: 'profiles#ban'
  resources :profiles

  get 'additions/create/:story_id' => 'additions#create'
  delete 'additions' => 'additions#delete'

  get 'comments/new/:id', to: 'comments#new'
  resources :comments

  post 'membership_cards/exchange', to: 'membership_cards#exchange'
  get 'membership_cards/exchange', to: 'membership_cards#exchange'

  get 'connections/search', to: 'connections#search'
  get 'connections/index', to: 'connections#search'

  resources :pages, :only => :show

  resources :payments, only: [:show, :destroy] do
    collection do
      get :success
      get :cancel
      post :notify
    end
  end
  get 'payment/create/:id', to: 'payments#create_story_payment'
  get 'payment/donate', to: 'payments#donation_form'
  post 'payment/donate', to: 'payments#create_donation_payment'
  get 'payment/be_premium', to: 'payments#create_mc_payment'

  get '*path' => "cuatro_cero_cuatro#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :icon, presence: true

  has_many :has_categories
  has_many :stories, through: :has_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @categories=Category.all
  end

  def show
    begin
      @category=set_category
    rescue ActiveRecord::RecordNotFound => e
      render 'errors/not_found'
    end
  end

  def new
    @category=Category.new
  end

  def edit
    @category=set_category
  end

  def create
    @category= Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def update
    @category=set_category
    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category=set_category
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category=Category.find(params[:id])
  end


  def category_params
     params.require(:category).permit(:name,:description,:icon)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<script>
  document.onload=function(){
    previewFile();  //calls the function named previewFile()
  }
  function previewFile(){
    var preview = document.querySelector('img'); //selects the query named img
    var file    = document.querySelector('input[type=file]').files[0]; //sames as here
    var reader  = new FileReader();

    reader.onloadend = function () {
      preview.src = reader.result;
      document.getElementById("category_icon").setAttribute("value",reader.result);
    }

    if (file) {
      reader.readAsDataURL(file); //reads the data as a URL

    } else {
      preview.src = "";
    }
  }
</script>

<% name ||= "Crear" %>
<h1><%= name %> Género</h1>
<%= form_for(@category) do |cat|%>
    <% @category.errors.full_messages.each do |message| %>
        <div class="error">
          *<%= message  %>
        </div>
    <% end %>
    <div class="field">
      <%= cat.text_field :name, placeholder: "Nombre del género", class:"form-field" %>
    </div>
    <div class="field">
        <%= cat.text_area :description, placeholder: "Descripción del género" %>
    </div>
    <div class="field">
      <input type="file" onchange="previewFile()"><br>
      <img src="<%=@category.icon %>" height="200" alt="Imagen actual">
    </div>
    <%=hidden_field(:category,:icon)%>
    <div class="buttons">
      <%= cat.submit "Guardar", class:"btn btn-default" %>
      <%= link_to "Volver", categories_path,class: "btn btn-default" %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<%= render "categories/form", name: "Editar" %>

app/views/categories/index.html.erb
<div class="row">

  <div class="jumbotron jumbo-cat col-md-10 col-md-offset-1 text-center">
    
    <h2><b>Géneros</b></h2>
    
    <div class="row">
      <% @categories.each do |category|%>
      <div class="col-md-4 category">
        <a href="/categories/<%=category.id%>">
          <img src="<%=category.icon %>" height="50" />
          <span>&nbsp;<%=category.name%></span>
        </a>
      </div>
      <% end %>
    </div>

    <% if user_signed_in? and (current_user.role_type == 'Administrator') %>
    <div class="text-center button-new-cat">
      <%= link_to 'Nuevo género', new_category_path, class: 'btn btn-main' %>
    </div>
    <% end %>

  </div>

</div>

app/views/categories/new.html.erb
<%= render "categories/form", name: "Nuevo" %>

app/views/categories/show.html.erb
<div class="container">

  <div class="row">

    <div class="col-md-3 text-center">
      <h1><%= @category.name  %></h1>
      <% cat = I18n.transliterate(@category.name).downcase %>
      <img class="img-responsive" src="/assets/categories_covers/<%= cat %>.jpg">
      <h4><%= @category.description %></h4>
      <hr/>
      <div class="text-center">
        <% if user_signed_in? and (current_user.role_type == 'Administrator') %>
        <%= link_to "Editar", edit_category_path(@category), class:"btn btn-main"  %>
        <%= link_to "Eliminar", @category, method: :delete, class:"btn btn-main"  %>
        <% end %>
        <%= link_to "Atrás", categories_path, class:"btn btn-main"  %>
      </div>
    </div>

    <div class="col-md-9 text-center">
      <h3>Historias</h3>
      <hr/>
      <div class="row">
        <% @category.stories.each do |story| %>
        <div class="col-md-3">
          <%= render 'stories/story_slot', story: story %>
        </div>
        <% end %>
      </div>
    </div>

  </div>

</div>