config/routes.rb
Rails.application.routes.draw do

  get 'connections/search'

  get 'membership_cards/exchange'
  get 'membership_cards/why'
  get 'membership_cards/generate'

  match "/404", :to => "errors#not_found", :via => :all
  match "/423", :to => "errors#permission_denied", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/503", :to => "errors#service_down", :via => :all

  get "auth/twitter/callback" => "identity#create_session"
  get "auth/facebook/callback" => "identity#create_session"

  devise_for :user

  get 'welcome/index'
  get 'maker/:id' => 'maker#show'
  get 'welcome/textoDesplegable'
  get 'welcome/wololo'

  root 'welcome#index'

  resources :categories

=begin t
  resource :request_friendships
  get 'request_friendships/send_request/:recipient', to: 'request_friendships#send_request'
  post 'request_friendships/creates', to: 'request_friendships#creates'
  get 'request_friendships/deciding_request/:rf/:choice', to: 'request_friendships#deciding_request'
  get 'request_friendships/show_pending', to: 'request_friendships#show_pending'
  get 'request_friendships/cancel_friendship', to: 'request_friendships#cancel_friendship'
=end

  get 'stories/read'
  get 'stories/read/:id' => 'stories#dbread' # read from DB
  get 'stories/example' => 'stories#example' # Caperucita Roja
  get 'stories/acquired' => 'stories#acquired'
  get 'stories/created' => 'stories#created'
  get 'stories/search', to: 'stories#search'
  resources :stories

  get 'chapters/:id' => 'chapters#show'
  post 'chapters' => 'chapters#create'
  post 'chapter_options' => 'chapters#create_options'
  put 'chapters' => 'chapters#update'
  delete 'chapters' => 'chapters#destroy'

  post 'options' => 'options#create'
  put 'options' => 'options#update'
  delete 'options' => 'options#destroy'

  get 'profiles/premium/:id', to: 'profiles#premium'
  get 'profiles/follow/:id', to: 'profiles#follow'
  get 'profiles/unfollow/:id', to: 'profiles#unfollow'
  get 'profiles/ban/:id', to: 'profiles#ban'
  resources :profiles

  get 'additions/create/:story_id' => 'additions#create'
  delete 'additions' => 'additions#delete'

  get 'comments/new/:id', to: 'comments#new'
  resources :comments

  post 'membership_cards/exchange', to: 'membership_cards#exchange'
  get 'membership_cards/exchange', to: 'membership_cards#exchange'

  get 'connections/search', to: 'connections#search'
  get 'connections/index', to: 'connections#search'

  resources :pages, :only => :show

  resources :payments, only: [:show, :destroy] do
    collection do
      get :success
      get :cancel
      post :notify
    end
  end
  get 'payment/create/:id', to: 'payments#create_story_payment'
  get 'payment/donate', to: 'payments#donation_form'
  post 'payment/donate', to: 'payments#create_donation_payment'
  get 'payment/be_premium', to: 'payments#create_mc_payment'

  get '*path' => "cuatro_cero_cuatro#index"

end

app/models/request_friendship.rb
class RequestFriendship < ActiveRecord::Base
  has_one :sender, class_name: "User", :foreign_key => "sender_id"
  has_one :recipient, class_name: "User", :foreign_key => "recipient_id"
  has_many :friendships

  validates :message, :status, presence: true
  validates :status, :inclusion => { :in => ["PENDING", "REJECTED", "ACCEPTED"] }
end

app/controllers/request_friendships_controller.rb
class RequestFriendshipsController < ApplicationController
  before_action :set_request_friendship, only: [:show, :edit, :update, :destroy, :cancel_friendship]
  before_action :authenticate_user!

  # GET /request_friendships
  # GET /request_friendships.json
  def index
    @request_friendships = RequestFriendship.all
  end

  # GET /request_friendships/1
  # GET /request_friendships/1.json
  def show
  end

  # GET /request_friendships/new
  def new
    @request_friendship = RequestFriendship.new
  end

  # GET /request_friendships/1/edit
  def edit
  end

  # POST /request_friendships
  # POST /request_friendships.json
  def create
    @request_friendship = RequestFriendship.new(request_friendship_params)

    respond_to do |format|
      if @request_friendship.save
        format.html { redirect_to @request_friendship, notice: 'La solicitud de amistad se ha creado correctamente' }
        format.json { render :show, status: :created, location: @request_friendship }
      else
        format.html { render :new }
        format.json { render json: @request_friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_friendships/1
  # PATCH/PUT /request_friendships/1.json
  def update
    respond_to do |format|
      if @request_friendship.update(request_friendship_params)
        format.html { redirect_to @request_friendship, notice: 'La solicitud de amistad se ha actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @request_friendship }
      else
        format.html { render :edit }
        format.json { render json: @request_friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_friendships/1
  # DELETE /request_friendships/1.json
  def destroy
    @request_friendship.destroy
    respond_to do |format|
      format.html { redirect_to request_friendships_url, notice: 'La solicitud de amistad fue eliminada con éxito.' }
      format.json { head :no_content }
    end
  end



  ## De aquí para arriba es scaffold, vale para un ADMIN, pero de aquí para abajo vamos a pensar las cosas...
  # GET introducir recipient en la URL

  #send_request/:recipient
  def send_request
    a = current_user.id
    @request_friendship = RequestFriendship.new({message: "", status: "PENDING", sender_id: a, recipient_id: params[:recipient]})
  end

  #Método especifico del clasico create - POST
  def creates
    result = RequestFriendship.new
    result.sender_id = current_user.id
    result.status = "PENDING"
    result.recipient_id = params[:request_friendship][:recipient_id]
    result.message = params[:request_friendship][:message]



    respond_to do |format|
      if result.save
        format.html { redirect_to welcome_index_path, notice: 'La solicitud de amistad se ha creado correctamente.' }
      else
        @request_friendship = result
        format.html { render :new }
      end
    end
  end


  #Dado la id (de la request_friendship :rf) - Es como un update
  def deciding_request
    request_friendship = RequestFriendship.find(params[:rf])

    n = current_user.id
    if n != request_friendship.recipient_id
      throw Exception
    end


    #Para que no sea grande ni saque datos explicitos ponemos un número 1 = ACCEPTED, 2 = REJECTED
    choice = "ACCEPTED"
    if (params[:choice] == "2")
      choice = "REJECTED"
    end


    result = RequestFriendship.where({recipient_id: current_user.id, sender_id: request_friendship.sender_id,
      status: "PENDING"}).last

    message_suffix = ""
    respond_to do |format|
      if result.update({status: choice})
        if(choice == "ACCEPTED")
          Friendship.createFriendship(result)
          message_suffix = "ACEPTADO"
        else
          message_suffix = "DENEGADO"
        end
        format.html { redirect_to welcome_index_path, notice: 'La petición se ha ' << message_suffix }
      else
        format.html { render 'welcome/index' }
      end
    end

  end



  def show_pending
    @request_friendships = RequestFriendship.where({recipient_id: current_user.id, status: "PENDING"})
  end


  def cancel_friendship
    # Comprueba que el loguado esté en esa friendship
    user1 = User.find(@request_friendship.sender_id)
    user2 = User.find(@request_friendship.recipient_id)

    if !(checkPrincipal?(user1) or
      checkPrincipal?(user2))

    raise 'Operacion no permitida'

    end



    # Si alguna operación falla no tiene efecto en la base de datos
    ActiveRecord::Base.transaction do
      @request_friendship.friendships.each do |fr|
        Friendship.find(fr.id).destroy!
      end
      @request_friendship.update!({status: "REJECTED"})
    end

    render 'welcome/index'

  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_request_friendship
    @request_friendship = RequestFriendship.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def request_friendship_params
    params.require(:request_friendship).permit(:message, :status, :sender_id, :recipient_id)
  end

end

app/helpers/request_friendships_helper.rb
module RequestFriendshipsHelper
end

app/views/request_friendships/_form.html.erb
<%= simple_form_for(@request_friendship) do |f| %>
  <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :message, type: "text-field", placeholder: "Introduzca un mensaje" %>

      <%= f.input :recipient_id, placeholder: "Recipient ID" %>

      <%= f.input :sender_id, placeholder: "Sender ID" %>

      <%= f.input :status, placeholder: "PENDING|ACCEPTED|REJECTED" %>



  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/request_friendships/edit.html.erb
<h1>Editing Request Friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @request_friendship %> |
<%= link_to 'Back', request_friendships_path %>

app/views/request_friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Request Friendships</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @request_friendships.each do |request_friendship| %>
      <tr>
        <td><%= link_to 'Show', request_friendship %></td>
        <td><%= link_to 'Edit', edit_request_friendship_path(request_friendship) %></td>
        <td><%= link_to 'Destroy', request_friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request friendship', new_request_friendship_path %>

app/views/request_friendships/new.html.erb
<h1>New Request Friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', request_friendships_path %>

app/views/request_friendships/send_request.html.erb
<%= simple_form_for(@request_friendship, :url => "/request_friendships/creates", :method => :post) do |f| %>
  <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :message, type: "text-field", placeholder: "Introduzca un mensaje" %>

      <%= f.hidden_field :recipient_id, value: @request_friendship.recipient_id %>

      <%= f.hidden_field :sender_id, value: @request_friendship.sender_id %>

      <%= f.hidden_field :status, value: @request_friendship.status %>



  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/request_friendships/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_request_friendship_path(@request_friendship) %> |
<%= link_to 'Back', request_friendships_path %>

app/views/request_friendships/show_pending.html.erb
<p id="notice"><%= notice %></p>
<h1>Peticiones pendientes</h1>
  <div class="container-fluid">
    <% @request_friendships.each do |request_friendship| %>
    <div class="row">
      <div class="col-md-12">
        <div class="section">
          <div class="container">
            <div class="row">
              <div class="col-md-3">
                <% a = Profile.where({user_id: request_friendship.sender_id}).first.avatar %>
                <%= image_tag( a, class: "img-circle") %>
              </div>
              <div class="col-md-9">
                <div class="row text-center">
                  <%= request_friendship.message %>

                </div>
                <br/>
                <div class="row">
                  <div class="col-md-6 text-right">
                    <%= link_to "Aceptar", "/request_friendships/deciding_request/#{request_friendship.id}/1", class: "btn btn-primary"  %>
                  </div>
                  <div class="col-md-6 text-left">
                      <%= link_to "Rechazar", "/request_friendships/deciding_request/#{request_friendship.id}/2", class: "btn btn-primary"  %>
                  </div>
                </div>
              </div>
              <div class="col-md-2">
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
    <% end %>

<%= link_to 'Back', request_friendships_path %>